# Generated by Django 2.1.8 on 2019-07-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190704_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tag_set',
            new_name='tag',
        ),
    ]
