# Generated by Django 2.1.8 on 2019-07-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190704_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
    ]
